version: '3.8'

services:
  comfyui:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - COMFYUI_AUTH_ENABLED=true
      - COMFYUI_DEFAULT_USER=nexusmind
      # Hash bcrypt para a senha 'NexusGenerative2026!'
      - "COMFYUI_DEFAULT_PASS_HASH=$$2b$$12$$QRgFSxlS67QPl4CbQXoakOP24Fia7pnUBqlrZYvQzNHQ5nQf7BlDW"
      - COMFYUI_API_TOKEN=zvztFnf9gNUkURYu7hYkKJlS5nFqpseSbo-jJ2q9chs
    ports:
      - "8188:8188"
    volumes:
      - comfyui_workspace_local:/workspace

volumes:
  comfyui_workspace_local:
