version: '3.8'

services:
  comfyui:
    image: heltonfraga/comfyui:latest
    environment:
      - WEB_ENABLE_AUTH=false
    ports:
      - "8188:8188"
    volumes:
      - comfyui_workspace_v2:/workspace

volumes:
  comfyui_workspace_v2:
