version: '3.8'

services:
  comfyui:
    image: heltonfraga/comfyui:latest
    environment:
      - WEB_ENABLE_AUTH=false
    volumes:
      - comfyui_workspace_v2:/workspace
    networks:
      - network_public
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=network_public"
        - "traefik.http.routers.comfyui.entrypoints=websecure"
        - "traefik.http.routers.comfyui.rule=Host(`comfyui.nexusmind.digital`)"
        - "traefik.http.routers.comfyui.priority=200"
        - "traefik.http.routers.comfyui.tls=true"
        - "traefik.http.routers.comfyui.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.comfyui.loadbalancer.server.port=8188"
        # ── Autenticação Básica (HARDCODED diretamente para resiliência no Portainer) ──
        # A senha gerada abaixo para 'nexusmind' é 'NexusGenerative2026!'
        - "traefik.http.middlewares.comfyui-auth.basicauth.users=nexusmind:$$apr1$$z5AMyJ1b$$XPkqxwBmT2foH8w8yjdOx."
        - "traefik.http.routers.comfyui.middlewares=comfyui-auth"

volumes:
  comfyui_workspace_v2:

networks:
  network_public:
    external: true